settings:
  log_folder: "/Users/sishai/data/my_code/helloWorld/logs"
  tenant_id: "c3c9dabe-1f88-4098-8b3a-850a742db76a"

test_cases:
  - id: 1
    randomize: false
    is_batch: true
    concurrent_workers: 1
    repetitions: 2
    requests_in_batch: 20
    request:
      method: "GET"
      url: "users/user1@sishaicyren.onmicrosoft.com/messages/AAMkAGY2NjI5NzU0LTQxYjktNGQ5My1hODY0LWYxNmM1Zjg1ZDNmZQBGAAAAAAANsx3zYZWoRbgJTxzNLUUrBwBKgViXObVQRKVrwdIXxyCeAAAAAAEMAABKgViXObVQRKVrwdIXxyCeAAARuI43AAA\u003d"
  - id: 2
    randomize: false
    is_batch: true
    concurrent_workers: 25
    repetitions: 30
    requests_in_batch: 1
    request:
      method: "GET"
      url: "users/user1@sishaicyren.onmicrosoft.com/messages/AAMkAGY2NjI5NzU0LTQxYjktNGQ5My1hODY0LWYxNmM1Zjg1ZDNmZQBGAAAAAAANsx3zYZWoRbgJTxzNLUUrBwBKgViXObVQRKVrwdIXxyCeAAAAAAEMAABKgViXObVQRKVrwdIXxyCeAAARuI43AAA\u003d"
  - id: 3
    randomize: false
    is_batch: true
    concurrent_workers: 25
    repetitions: 1
    requests_in_batch: 21
    request:
      method: "GET"
      url: "users/user1@sishaicyren.onmicrosoft.com/messages/AAMkAGY2NjI5NzU0LTQxYjktNGQ5My1hODY0LWYxNmM1Zjg1ZDNmZQBGAAAAAAANsx3zYZWoRbgJTxzNLUUrBwBKgViXObVQRKVrwdIXxyCeAAAAAAEMAABKgViXObVQRKVrwdIXxyCeAAARuI43AAA\u003d"

